Learn 273
betrybe/pytest-evaluator-action pull request #1
Opened 2020-09-16 19:46 UTC by eucleciojosias

Atlassian board issue:
[EdOps - LEARN-273](https://trybe.atlassian.net/browse/LEARN-273?atlOrigin=eyJpIjoiZmNmYzQxNmE2ZDkzNDM4ZWI1ZWNmZGZlOTMzY2NmY2QiLCJwIjoiaiJ9)

PR de teste usando a nova action:
https://github.com/tryber/sd-01-tech-news/pull/9

Check que gerou o resultado do avaliador do Pytest com sucesso:
https://github.com/tryber/sd-01-tech-news/pull/9/checks?check_run_id=1125284881

2020-09-17 01:42 UTC, jeanpsv requested changes
@eucleciojosias seria ótimo se já pudesse configurar o CI executando os testes unitários, oq vc acha?

2020-09-17 01:42 UTC, jeanpsv commented on Dockerfile
> +ENTRYPOINT ["/home/entrypoint.sh"]
adiciona uma nova linha ao final do arquivo

2020-09-17 01:42 UTC, jeanpsv commented on entrypoint.sh
> +git clone https://github.com/$GITHUB_REPOSITORY.git /github/master-repo/
Nas versões mais recentes dos avaliadores nós passamos o repositório e a _branch_ como parâmetros para o avaliador (lembrar de adicionar na documentação)

2020-09-17 01:42 UTC, jeanpsv commented on entrypoint.sh
> +cp -r /github/master-repo/tests /github/workspace
Não entendi essa parte. Pq remover a pasta `/github/workspace/tests`?

O repositório de testes deve ser inteiramente copiado e não apenas a pasta `tests`

2020-09-17 01:42 UTC, jeanpsv commented on entrypoint.sh
> +echo ::set-output name=pr-number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
Não é necessário coletar o número do PR dessa forma, podemos remover essa parte (e tbm da documentação).

O número do PR é coletado através de `${{ github.event.number }}`

2020-09-17 01:42 UTC, jeanpsv commented on src/evaluation.py
> +            "identifier": req['identifier'],
Originalmente o campo `identifier` não é padrão para as avaliações, utilizamos ele durante a avaliação dos projetos de banco de dados. É necessário utilizar esse campo?

2020-09-17 13:10 UTC, eucleciojosias commented on entrypoint.sh
> +cp -r /github/master-repo/tests /github/workspace
@jeanpsv eu não veja a necessidade de criar um repositório de testes pelos seguintes pontos (se puder confirmar):
- A branch master terá os testes originais feito pela nossa equipe
- A branch master não será modificada após a disponibilização do projeto
- Logo, ao fazer o clone da master, já garantiremos que os testes serão os originais
- Assim sendo, eu apenas pego os testes originais de `/github/master-repo/tests` e coloco no diretório de testes do aluno `/github/workspace/tests`, assim qualquer modificações nos testes do aluno serão sobrescritos
- Não copio tudo pois sobrescreveria o código do aluno

2020-09-17 14:16 UTC, eucleciojosias commented on Dockerfile
> +ENTRYPOINT ["/home/entrypoint.sh"]
Feito.

2020-09-17 14:16 UTC, eucleciojosias commented on entrypoint.sh
> +git clone https://github.com/$GITHUB_REPOSITORY.git /github/master-repo/
Feito.

2020-09-17 14:16 UTC, eucleciojosias commented on entrypoint.sh
> +echo ::set-output name=pr-number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
Feito.

2020-09-17 14:16 UTC, eucleciojosias commented on src/evaluation.py
> +            "identifier": req['identifier'],
Removido.

2020-09-17 22:04 UTC, jeanpsv commented on entrypoint.sh
> +cp -r /github/master-repo/tests /github/workspace
Boa @eucleciojosias , concordo com vc.

2020-09-17 22:08 UTC, jeanpsv requested changes

2020-09-17 22:08 UTC, jeanpsv commented on README.md
> +      "identifier": "test_desafio1",
É necessário o `identifier` aqui?

2020-09-17 22:08 UTC, jeanpsv commented on action.yml
> +  image: 'Dockerfile'
é necessário passar os parametros `inputs` para a imagem aqui

2020-09-18 13:05 UTC, eucleciojosias commented on README.md
> +      "identifier": "test_desafio1",
Sim, no `requirements` que a Trybe vai montar é necessário pois este será o identificador usado no _script_ python

2020-09-18 17:51 UTC, eucleciojosias commented on action.yml
> +  image: 'Dockerfile'
Feito.

2020-09-18 21:26 UTC, inaC requested changes

2020-09-18 21:26 UTC, inaC commented on tests/test_evaluation.py
> +    reqs = load_file(req_mock)
Você poderia renomear as seguintes variáveis de forma a torná-las mais explícitas:
* `reqs` -> `requirements`
* `res` -> `result`
* `tests_eval` -> `evaluations`

2020-09-20 22:18 UTC, jeanpsv approved these changes
Só ajustar e discutir os pontos que o @inaC apontou e boas.

2020-09-20 22:20 UTC, jeanpsv commented
@eucleciojosias Na verdade, acredito que vale a pena documentar como dever ser feitos os testes para que essa _action_ funcione corretamente. Oq vc acha?

2020-09-21 18:38 UTC, eucleciojosias commented on README.md
> +      "identifier": "test_desafio2",
@inaC sim

2020-09-21 18:48 UTC, eucleciojosias commented on tests/fixture/report.json
> +            "Python": "3.7.7",
Isso é só uma fixture, a versão instalada no container do [avaliador](https://github.com/tryber/sd-01-tech-news/pull/9/checks?check_run_id=1125284881#step:5:54) é a `3.8` . Mas vou alterar aqui tb

2020-09-21 18:49 UTC, eucleciojosias commented on tests/test_evaluation.py
> +import src.evaluation as ev
Também não sou fã de abreviação, mas como no python é comum acabei usando. Concordo que fica melhor não-abreviado

2020-09-21 18:54 UTC, eucleciojosias commented on tests/test_evaluation.py
> +    assert tests_eval[0]['grade'] == ev.PASSED_GRADE
Discordo, não acho uma boa prática escrever valores _hardcoded_, _enums_ além de ficar darem significado (o que 3 significa?) também, em caso de mudar o valor de `PASSED_GRADE` não preciso alterar em todo o teste que está usando, altero só a enum e automaticamente todos os testes devem ter o novo valor nestes cenários. Se alguém mudar então é porque é um requisito da tarefa, não? Alguém mudar sem ter necessidade deve ser questionado no CR o porquê da mudança, pois vai afetar o _evluator store_.

2020-09-21 19:05 UTC, eucleciojosias commented on tests/test_evaluation.py
> +    assert tests_eval[0]['grade'] == ev.PASSED_GRADE
A função deste teste é validar que dado determinario cenário, o valor deve ser o de `passed grade`, independentemente do valor que é usado.

2020-09-21 19:10 UTC, eucleciojosias commented on tests/test_evaluation.py
> +    assert tests_eval[0]['grade'] == ev.PASSED_GRADE
Pensando na tua preocupação eu criei um teste que valida as _enums_, dessa forma se for alterado vai quebrar este teste

2020-09-21 22:53 UTC, inaC requested changes

2020-09-21 22:53 UTC, inaC commented on tests/test_evaluation.py
> +    evaluation.PASSED_GRADE == 3
Dessa forma os testes sempre passarão para essa função, é preciso do `assert`.
Você pode testar se fazer `evaluation.FAILED_GRADE == 'foo'` e escrever no terminal `make test`, que vai passar, sendo que não deveria. Logo, você poderia mudar para o seguinte 🙂 :
```suggestion
    assert evaluation.FAILED_GRADE == 1
    assert evaluation.PASSED_GRADE == 3
```

2020-09-22 11:58 UTC, eucleciojosias commented on tests/test_evaluation.py
> +    evaluation.PASSED_GRADE == 3
Realmente esqueci disso hehehe

2020-09-22 13:12 UTC, LeandroLM approved these changes

2020-09-22 13:12 UTC, LeandroLM commented on src/evaluation.py
> +        raise ValueError("You must pass report and requirements files as argument!")
```suggestion
        raise ValueError("You must pass report and requirements files as arguments!")
```

2020-09-22 13:22 UTC, inaC commented on tests/test_evaluation.py
> +    evaluation.PASSED_GRADE == 3
De boas mano 🙂

2020-09-22 13:24 UTC, inaC approved these changes

2020-09-23 11:41 UTC, merged