Prepara avaliador para versão v3
betrybe/pytest-evaluator-action pull request #8
Opened 2021-01-25 22:57 UTC by jeanpsv

2021-01-25 23:03 UTC, eucleciojosias requested changes

2021-01-25 23:03 UTC, eucleciojosias commented on entrypoint.sh
>  # Run evaluator over pytest result assuring that the requirements file is the original
O comentário era pra esclarecer pq era passado da pasta `main-branch`, agora não se faz mais necessário
```suggestion
```

2021-01-25 23:22 UTC, eucleciojosias commented on entrypoint.sh
>  # Run evaluator over pytest result assuring that the requirements file is the original
O comentário era pra "justificar"o pq de estar passando o `requirements.json` da pasta `main-branch`, agora não tem motivo pra ter o comentário.

2021-01-25 23:22 UTC, eucleciojosias commented
Não seria a `v2`?

2021-01-26 10:56 UTC, jeanpsv commented on entrypoint.sh
>  # Run evaluator over pytest result assuring that the requirements file is the original
Ah entendi agora, vou remover

2021-01-26 10:58 UTC, jeanpsv commented
> Não seria a `v2`?

`v3` da avaliação em geral. Antes dessa forma atual, eu criei uma versão beeem manual 😬

2021-01-26 13:41 UTC, inaC approved these changes

2021-01-26 17:42 UTC, eucleciojosias approved these changes

2021-01-28 18:14 UTC, merged