Aceita xfailed como sucesso
betrybe/pytest-evaluator-action pull request #9
Opened 2021-07-07 13:21 UTC by barraponto

No pytest, é possível marcar testes como `xfail`: espera-se que falhe.
Existe um recurso alternativo, `pytest.raises` que confirma que a implementação lança exceções nas condições esperadas. Mas `xfail` é o recomendado pro caso de implementações incompletas ou incorretas.

O novo projeto [Job Insights][https://github.com/betrybe/sd-0x-project-job-insights-rubric] é o primeiro projeto em python que pede pras pessoas estudantes escreverem testes originais e oferece implementações imperfeitas que _devem_ falhar -- espera-se que o teste da estudante pegue as falhas.

Para esse novo projeto (e pra futuros projetos), nosso evaluator precisa considerar `xfailed` como uma saída aceitável pros testes.

2021-07-07 14:28 UTC, eucleciojosias requested changes

2021-07-07 14:28 UTC, eucleciojosias commented on src/evaluation.py
> +        if test_result['outcome'] in ACCEPTABLE_OUTCOMES:
Seria bom criar um teste unitário para validar esta mudança

2021-07-08 20:40 UTC, barraponto commented on src/evaluation.py
> +        if test_result['outcome'] in ACCEPTABLE_OUTCOMES:
Atualizado, Wes!

2021-07-08 21:43 UTC, eucleciojosias approved these changes

2021-07-08 21:43 UTC, eucleciojosias commented on tests/fixture/requirements.json
> +      "identifier": "tests/sorting/test_sorting.py::test_sort_by[sort_by_strings]",
Aqui poderia ser só o nome da função do teste, de qualquer forma vai funcionar xD
```suggestion
      "identifier": "test_sort_by[sort_by_strings]",
```

2021-07-12 17:35 UTC, LeandroLM approved these changes

2021-07-12 18:53 UTC, merged